[package]
name = "service"
version = "0.2.4"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
crate-type = ["dylib", "lib"]
name = "service"

[dependencies]
constants = { path = "../../../libs/constants" }
basic = { path = "../../../libs/basic" }
macros = { path = "../../../libs/macros" }
cgroup = { path = "../../../libs/cgroup" }
event = { path = "../../../libs/event" }
watchdog = { path = "../../../libs/watchdog" }
core = { path = "../../libcore" }

nix = "0.24"
log = { version = "=0.4.14", default_features = false, features = ["std"] }
serde = "1.0.130"
confique = { version = "0.1.3", default-features = false, features = ['toml'] }
libc = "0.2.*"
once_cell = { version = "=1.7.2" }


[dev-dependencies]
libtests = { path = "../../../libs/libtests" }

[features]
default = ["noplugin"]
noplugin = []
