[package]
name = "hostname_setup"
version = "0.2.4"
edition = "2021"

[dependencies]
nix = "0.24"
log = { version = "=0.4.14", default_features = false, features = ["std"] }
libc = "0.2.*"
constants = { path = "../../libs/constants" }
basic = { path = "../../libs/basic" }
