[package]
name = "mount"
version = "0.2.4"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
crate-type = ["dylib", "lib"]
name = "mount"

[dependencies]
event = { path = "../../../libs/event" }
macros = { path = "../../../libs/macros" }
basic = { path = "../../../libs/basic" }
core = { path = "../../libcore" }

nix = "0.24"
log = "0.4"
epoll = "4.3.1"
libc = "0.2.*"
serde = "1.0.130"
once_cell = { version = "1.5.2" }

[features]
default = ["noplugin"]
noplugin = []
