[package]
name = "sctl"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = { version = "3.1.8", features = ["derive"] }
cmdproto = { path = "../../libs/cmdproto" }
basic = { path = "../../libs/basic" }
nix = "0.24"
constants = { path = "../../libs/constants" }
