[package]
name = "socket"
version = "0.5.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
crate-type = ["dylib", "lib"]
name = "socket"

[dependencies]
basic = { path = "../../../libs/basic", features = ["io"] }
constants = { path = "../../../libs/constants" }
core = { path = "../../libcore", default-features = false }
event = { path = "../../../libs/event" }
macros = { path = "../../../libs/macros" }

confique = { version = "0.1.3", default-features = false, features = ["toml"] }
log = { version = "=0.4.14", default_features = false }
nix = { version = "0.24", default-features = false }
once_cell = { version = "=1.7.2", default-features = false }
serde = { version = "1.0.130", default-features = false }

[dev-dependencies]
libtests = { path = "../../../libs/libtests" }

[features]
default = ["noplugin"]
noplugin = []
