[package]
name = "rc-local-generator"
version = "0.2.4"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
log = { version = "=0.4.14", default_features = false, features = ["std"] }
libc = { version = "0.2" }
