[package]
name = "rc-local-generator"
version = "0.5.1"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
log = { path = "../../libs/log" }
libc = { version = "0.2", default-features = false }
